-- ACKS Arbiter — Canonical Database Schema
-- This file always reflects the current database state after all migrations.
-- Do NOT edit this file directly. Add a new migration in db/migrations/ instead.
-- Last migration applied: 044
--
-- To rebuild from scratch: delete campaign.db and relaunch the game.

CREATE TABLE IF NOT EXISTS schema_migrations (
    version INTEGER PRIMARY KEY,
    applied_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Migration 034: Schema sweep markers
CREATE TABLE IF NOT EXISTS schema_sweep_markers (
    sweep_name TEXT PRIMARY KEY,
    applied_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Migration 001: Initial schema
-- Creates all Tier 1 tables: campaigns, characters, parties, party_members,
-- character_conditions, character_proficiencies, inventory_items, character_spells,
-- hex_maps, hex_cells, domains.

CREATE TABLE IF NOT EXISTS campaigns (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    world_name TEXT NOT NULL DEFAULT '',
    calendar_day INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    is_active INTEGER NOT NULL DEFAULT 1 CHECK(is_active IN (0, 1))
);

CREATE TABLE IF NOT EXISTS characters (
    id TEXT PRIMARY KEY,
    campaign_id TEXT NOT NULL REFERENCES campaigns(id),
    name TEXT NOT NULL,
    character_type TEXT NOT NULL DEFAULT 'pc'
        CHECK(character_type IN ('pc', 'henchman', 'npc')),
    persistence_tier TEXT NOT NULL DEFAULT 'full'
        CHECK(persistence_tier IN ('full', 'named', 'transient')),
    race TEXT NOT NULL DEFAULT 'human',
    character_class TEXT NOT NULL DEFAULT 'fighter',
    level INTEGER NOT NULL DEFAULT 1,
    xp INTEGER NOT NULL DEFAULT 0,
    -- Four ACKS 1e combat progression types. "crusader" is ACKS II only.
    combat_progression TEXT NOT NULL DEFAULT 'fighter'
        CHECK(combat_progression IN ('fighter', 'cleric', 'thief', 'mage')),
    strength INTEGER NOT NULL DEFAULT 10,
    intelligence INTEGER NOT NULL DEFAULT 10,
    wisdom INTEGER NOT NULL DEFAULT 10,
    dexterity INTEGER NOT NULL DEFAULT 10,
    constitution INTEGER NOT NULL DEFAULT 10,
    charisma INTEGER NOT NULL DEFAULT 10,
    hp_max INTEGER NOT NULL DEFAULT 1,
    hp_current INTEGER NOT NULL DEFAULT 1,
    armor_class INTEGER NOT NULL DEFAULT 0,
    attack_throw INTEGER NOT NULL DEFAULT 10,
    is_dead INTEGER NOT NULL DEFAULT 0 CHECK(is_dead IN (0, 1)),
    is_active INTEGER NOT NULL DEFAULT 1 CHECK(is_active IN (0, 1)),
    employer_id TEXT REFERENCES characters(id),
    loyalty_score INTEGER,
    wage_gp_per_month INTEGER,
    -- Migration 005 additions
    save_petrification INTEGER NOT NULL DEFAULT 15,
    save_poison_death INTEGER NOT NULL DEFAULT 14,
    save_blast_breath INTEGER NOT NULL DEFAULT 16,
    save_staffs_wands INTEGER NOT NULL DEFAULT 16,
    save_spells INTEGER NOT NULL DEFAULT 17,
    base_movement INTEGER NOT NULL DEFAULT 120,
    hit_die_type TEXT NOT NULL DEFAULT '1d8',
    max_level INTEGER NOT NULL DEFAULT 14,
    xp_for_next_level INTEGER NOT NULL DEFAULT 2000,
    xp_adjustment_percent INTEGER NOT NULL DEFAULT 0,
    title TEXT NOT NULL DEFAULT '',
    alignment TEXT NOT NULL DEFAULT 'neutral',
    current_age INTEGER NOT NULL DEFAULT 0,
    age_category TEXT NOT NULL DEFAULT 'adult',
    languages TEXT NOT NULL DEFAULT '[]',
    personality TEXT NOT NULL DEFAULT '{}',
    is_incapacitated INTEGER NOT NULL DEFAULT 0,
    -- Migration 008 additions
    portrait_id TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    -- Migration 009 additions
    sex TEXT NOT NULL DEFAULT 'male' CHECK(sex IN ('male', 'female')),
    -- Migration 026 additions
    token_variant TEXT NOT NULL DEFAULT '',
    -- Migration 040: class-specific sub-selections (JSON dict)
    -- e.g. {"regional_origin": "jutland"} for barbarians,
    -- {"witch_tradition": "sylvan"} for witches.
    class_metadata TEXT NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS parties (
    id TEXT PRIMARY KEY,
    campaign_id TEXT NOT NULL REFERENCES campaigns(id),
    name TEXT NOT NULL DEFAULT 'The Party',
    current_map_id TEXT,
    current_hex_q INTEGER,
    current_hex_r INTEGER,
    current_location_type TEXT NOT NULL DEFAULT 'wilderness'
        CHECK(current_location_type IN ('wilderness', 'dungeon', 'settlement', 'sea')),
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    -- Migration 038: heraldry builder FK (NULL → backfilled at session load)
    heraldry_id TEXT REFERENCES party_heraldry(heraldry_id)
);

-- Migration 038: per-party heraldic shield.
CREATE TABLE IF NOT EXISTS party_heraldry (
    heraldry_id         TEXT PRIMARY KEY,
    shape_id            TEXT NOT NULL DEFAULT 'heater',
    division_id         TEXT NOT NULL DEFAULT 'plain',
    tincture_primary    TEXT NOT NULL DEFAULT '#dcdcdc',
    tincture_secondary  TEXT NOT NULL DEFAULT '#1a1a1a',
    ordinary_id         TEXT NOT NULL DEFAULT '',
    tincture_ordinary   TEXT NOT NULL DEFAULT '#dcdcdc',
    charge_id           TEXT NOT NULL DEFAULT '',
    tincture_charge     TEXT NOT NULL DEFAULT '#dcdcdc',
    created_at          TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS party_members (
    party_id TEXT NOT NULL REFERENCES parties(id),
    character_id TEXT NOT NULL REFERENCES characters(id),
    formation_slot TEXT NOT NULL DEFAULT 'middle'
        CHECK(formation_slot IN ('point', 'front', 'middle', 'rear')),
    -- Migration 022: grid-based formation (replaces formation_slot)
    formation_col INTEGER NOT NULL DEFAULT -1,
    formation_row INTEGER NOT NULL DEFAULT -1,
    joined_at TEXT NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY (party_id, character_id),
    -- Migration 035: enforce mutual exclusivity (one party per character)
    UNIQUE (character_id)
);

-- Migration 021: Party travel/exploration state
CREATE TABLE IF NOT EXISTS party_state (
    party_id TEXT PRIMARY KEY REFERENCES parties(id),
    marching_order TEXT NOT NULL DEFAULT '[]',
    is_lost INTEGER NOT NULL DEFAULT 0 CHECK(is_lost IN (0, 1)),
    is_force_marching INTEGER NOT NULL DEFAULT 0 CHECK(is_force_marching IN (0, 1)),
    force_march_days_used INTEGER NOT NULL DEFAULT 0,
    days_since_rest INTEGER NOT NULL DEFAULT 0,
    rations_days_remaining INTEGER NOT NULL DEFAULT 0,
    current_mount_type TEXT NOT NULL DEFAULT '',
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS character_conditions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    character_id TEXT NOT NULL REFERENCES characters(id),
    condition_name TEXT NOT NULL,
    applied_at_round INTEGER,
    expires_at_round INTEGER,
    source_id TEXT
);

CREATE TABLE IF NOT EXISTS character_proficiencies (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    character_id TEXT NOT NULL REFERENCES characters(id),
    proficiency_key TEXT NOT NULL,
    rank INTEGER NOT NULL DEFAULT 1,
    slot_type TEXT NOT NULL DEFAULT 'general'
        CHECK(slot_type IN ('class', 'general')),
    -- Migration 007 additions
    selections_count INTEGER NOT NULL DEFAULT 1,
    specialization TEXT NOT NULL DEFAULT ''
);

-- encumbrance_units: weight in 1/1000-stone units (1 stone = 1000 units = ~10 lbs)
-- Examples: dagger=167, sword=1000, plate armour=6000, coin/gem=1
CREATE TABLE IF NOT EXISTS inventory_items (
    id TEXT PRIMARY KEY,
    character_id TEXT NOT NULL REFERENCES characters(id),
    item_key TEXT NOT NULL,
    name TEXT NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    encumbrance_units INTEGER NOT NULL DEFAULT 0,
    slot TEXT NOT NULL DEFAULT 'pack'
        CHECK(slot IN (
            'hands_main', 'hands_off',
            'body', 'head', 'belt', 'feet', 'hands_worn', 'cloak',
            'accessory_1', 'accessory_2', 'accessory_3', 'accessory_4', 'accessory_5',
            'pack', 'mount'
        )),
    is_equipped INTEGER NOT NULL DEFAULT 0 CHECK(is_equipped IN (0, 1)),
    notes TEXT NOT NULL DEFAULT '',
    -- Migration 005 additions
    item_category TEXT NOT NULL DEFAULT 'gear',
    is_magical INTEGER NOT NULL DEFAULT 0,
    magical_bonus INTEGER NOT NULL DEFAULT 0,
    weapon_damage TEXT NOT NULL DEFAULT '',
    armor_ac_bonus INTEGER NOT NULL DEFAULT 0,
    is_heavy INTEGER NOT NULL DEFAULT 0,
    -- Migration 006 additions
    damage_type TEXT NOT NULL DEFAULT 'physical',
    material TEXT NOT NULL DEFAULT '',
    -- Migration 010 additions
    container_id TEXT NOT NULL DEFAULT '',
    -- Migration 011: slot expanded to include feet, hands_worn, accessory_1-5
    -- Migration 012 additions
    uses_remaining INTEGER NOT NULL DEFAULT -1,
    -- Migration 021 additions
    party_id TEXT REFERENCES parties(id) DEFAULT NULL,
    -- Migration 023 additions
    creature_id TEXT REFERENCES trained_creatures(id) DEFAULT NULL,
    -- Migration 024 additions
    vehicle_id TEXT REFERENCES draft_vehicles(id) DEFAULT NULL,
    -- Migration 032 additions
    location_cache_id TEXT REFERENCES location_caches(id) ON DELETE CASCADE DEFAULT NULL
);

-- trained_creatures: companion animals (mounts, war animals, pack animals, etc.).
-- Stats derived from monster_catalog.json via species_id at runtime.
-- Migration 023 addition.
CREATE TABLE IF NOT EXISTS trained_creatures (
    id TEXT PRIMARY KEY,
    campaign_id TEXT NOT NULL REFERENCES campaigns(id),
    -- Migration 035: party_id is required (NOT NULL)
    party_id TEXT NOT NULL REFERENCES parties(id),
    species_id TEXT NOT NULL,
    purchase_item_key TEXT NOT NULL DEFAULT '',
    name TEXT NOT NULL DEFAULT '',
    role TEXT NOT NULL DEFAULT 'L'
        CHECK(role IN ('M', 'WM', 'G', 'H', 'D', 'L', 'WB')),
    tricks_known TEXT NOT NULL DEFAULT '[]',
    trick_limit INTEGER NOT NULL DEFAULT 5,
    morale INTEGER NOT NULL DEFAULT 0,
    handler_id TEXT REFERENCES characters(id) DEFAULT NULL,
    introduced_handlers TEXT NOT NULL DEFAULT '[]',
    hp_current INTEGER NOT NULL DEFAULT 1,
    hp_max INTEGER NOT NULL DEFAULT 1,
    training_complete INTEGER NOT NULL DEFAULT 1 CHECK(training_complete IN (0, 1)),
    is_alive INTEGER NOT NULL DEFAULT 1 CHECK(is_alive IN (0, 1)),
    formation_col INTEGER NOT NULL DEFAULT -1,
    formation_row INTEGER NOT NULL DEFAULT -1,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- draft_vehicles: carts and wagons hitched to draft teams.
-- Capacity depends on the draft team composition (see acore_equipment.xml:623-628).
-- Migration 024 addition.
CREATE TABLE IF NOT EXISTS draft_vehicles (
    id TEXT PRIMARY KEY,
    campaign_id TEXT NOT NULL REFERENCES campaigns(id),
    party_id TEXT NOT NULL REFERENCES parties(id),
    item_key TEXT NOT NULL,
    name TEXT NOT NULL DEFAULT '',
    hitched_creatures TEXT NOT NULL DEFAULT '[]',
    is_destroyed INTEGER NOT NULL DEFAULT 0 CHECK(is_destroyed IN (0, 1)),
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- character_spells: active spell repertoire for all casters.
-- is_in_repertoire is always 1 for new rows (enforced by app logic).
-- is_memorized and memorized_slots are legacy; use character_spell_slots_expended instead.
CREATE TABLE IF NOT EXISTS character_spells (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    character_id TEXT NOT NULL REFERENCES characters(id),
    spell_key TEXT NOT NULL,
    spell_level INTEGER NOT NULL,
    is_memorized INTEGER NOT NULL DEFAULT 0 CHECK(is_memorized IN (0, 1)),
    is_in_repertoire INTEGER NOT NULL DEFAULT 1 CHECK(is_in_repertoire IN (0, 1)),
    memorized_slots INTEGER NOT NULL DEFAULT 0
);

-- Migration 018: Arcane spell formula tracking
-- Arcane only: spells for which the character possesses the formula.
-- Distinct from active repertoire (character_spells). Enables "known but not active" state.
CREATE TABLE IF NOT EXISTS character_spell_formulas (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    character_id TEXT NOT NULL REFERENCES characters(id),
    spell_key TEXT NOT NULL,
    spell_level INTEGER NOT NULL,
    UNIQUE(character_id, spell_key)
);

-- Migration 018: Daily expended spell slot tracking per level.
-- Replaces the per-spell is_memorized proxy. Cleared on rest.
CREATE TABLE IF NOT EXISTS character_spell_slots_expended (
    character_id TEXT NOT NULL REFERENCES characters(id),
    spell_level INTEGER NOT NULL,
    expended INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (character_id, spell_level)
);

CREATE TABLE IF NOT EXISTS hex_maps (
    id TEXT PRIMARY KEY,
    campaign_id TEXT NOT NULL REFERENCES campaigns(id),
    name TEXT NOT NULL,
    scale TEXT NOT NULL CHECK(scale IN ('campaign_24mi', 'regional_6mi', 'local_15mi')),
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- fog_state is per-campaign (scoped through hex_maps.campaign_id)
CREATE TABLE IF NOT EXISTS hex_cells (
    map_id TEXT NOT NULL REFERENCES hex_maps(id),
    q INTEGER NOT NULL,
    r INTEGER NOT NULL,
    elevation TEXT NOT NULL DEFAULT 'flat'
        CHECK(elevation IN ('flat', 'hills', 'mountains')),
    biome TEXT NOT NULL DEFAULT 'clear'
        CHECK(biome IN ('clear', 'woods', 'jungle', 'swamp', 'desert')),
    water TEXT NOT NULL DEFAULT ''
        CHECK(water IN ('', 'ocean', 'lake')),
    civilization TEXT NOT NULL DEFAULT 'wilderness'
        CHECK(civilization IN ('civilized', 'borderlands', 'wilderness')),
    has_city INTEGER NOT NULL DEFAULT 0 CHECK(has_city IN (0, 1)),
    original_biome TEXT NOT NULL DEFAULT '',
    fog_state TEXT NOT NULL DEFAULT 'hidden'
        CHECK(fog_state IN ('hidden', 'explored', 'visible')),
    PRIMARY KEY (map_id, q, r)
);

-- Migration 020: Hex overlays (rivers & roads)
-- Edge numbering: 0=N, 1=NE, 2=SE, 3=S, 4=SW, 5=NW (clockwise from North).
CREATE TABLE IF NOT EXISTS hex_overlays (
    map_id TEXT NOT NULL,
    q INTEGER NOT NULL,
    r INTEGER NOT NULL,
    overlay_type TEXT NOT NULL CHECK(overlay_type IN ('river', 'road')),
    edges TEXT NOT NULL DEFAULT '[]',
    flow_exit INTEGER NOT NULL DEFAULT -1,
    PRIMARY KEY (map_id, q, r, overlay_type),
    FOREIGN KEY (map_id) REFERENCES hex_maps(id)
);

CREATE TABLE IF NOT EXISTS domains (
    id TEXT PRIMARY KEY,
    campaign_id TEXT NOT NULL REFERENCES campaigns(id),
    name TEXT NOT NULL,
    owner_character_id TEXT REFERENCES characters(id),
    location_map_id TEXT REFERENCES hex_maps(id),
    location_hex_q INTEGER,
    location_hex_r INTEGER,
    -- Three ACKS territory classifications only
    territory_type TEXT NOT NULL DEFAULT 'wilderness'
        CHECK(territory_type IN ('civilized', 'borderlands', 'wilderness')),
    urban_families INTEGER NOT NULL DEFAULT 0,
    peasant_families INTEGER NOT NULL DEFAULT 0,
    morale INTEGER NOT NULL DEFAULT 0,
    garrison_troops INTEGER NOT NULL DEFAULT 0,
    revenue_gp INTEGER NOT NULL DEFAULT 0,
    expenses_gp INTEGER NOT NULL DEFAULT 0,
    net_income_gp INTEGER NOT NULL DEFAULT 0,
    domain_xp_this_month INTEGER NOT NULL DEFAULT 0,
    -- Migration 025: ruler used in reputation cascade (ruler -> domain -> settlement)
    ruler_npc_id TEXT REFERENCES characters(id),
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Migration 005: Character powers (modular power system)
CREATE TABLE IF NOT EXISTS character_powers (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    character_id TEXT NOT NULL REFERENCES characters(id),
    power_id TEXT NOT NULL,
    unlock_level INTEGER NOT NULL DEFAULT 1,
    conditions TEXT NOT NULL DEFAULT '[]',
    progression_data TEXT NOT NULL DEFAULT '{}',
    is_active INTEGER NOT NULL DEFAULT 1 CHECK(is_active IN (0, 1))
);

-- Migration 002: Override system tables

-- override_log: append-only audit trail. Never delete rows.
CREATE TABLE IF NOT EXISTS override_log (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    campaign_id TEXT NOT NULL REFERENCES campaigns(id),
    game_day INTEGER NOT NULL DEFAULT 0,
    game_round INTEGER NOT NULL DEFAULT 0,
    applied_at TEXT NOT NULL DEFAULT (datetime('now')),
    override_type TEXT NOT NULL,
    target_id TEXT NOT NULL DEFAULT '',
    field_changed TEXT NOT NULL DEFAULT '',
    old_value TEXT NOT NULL DEFAULT '',
    new_value TEXT NOT NULL DEFAULT ''
);

-- game_snapshots: capped at 10 per campaign (oldest auto-pruned on 11th save).
CREATE TABLE IF NOT EXISTS game_snapshots (
    id TEXT PRIMARY KEY,
    campaign_id TEXT NOT NULL REFERENCES campaigns(id),
    label TEXT NOT NULL,
    snapshot_data TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- dungeon_entrances: hex placement record; dungeon_data populated by layout generator.
CREATE TABLE IF NOT EXISTS dungeon_entrances (
    id TEXT PRIMARY KEY,
    campaign_id TEXT NOT NULL REFERENCES campaigns(id),
    map_id TEXT NOT NULL REFERENCES hex_maps(id),
    hex_q INTEGER NOT NULL,
    hex_r INTEGER NOT NULL,
    name TEXT NOT NULL DEFAULT 'Unknown Dungeon',
    dungeon_data TEXT NOT NULL DEFAULT ''
);

-- Migration 003: Dice roll log
-- Per-session only. Cleared on session end. Capped at 200 rows (DiceSystem auto-prunes oldest).

CREATE TABLE IF NOT EXISTS dice_rolls (
    id                  INTEGER  PRIMARY KEY AUTOINCREMENT,
    game_day            INTEGER  NOT NULL DEFAULT 0,
    roll_type           TEXT     NOT NULL DEFAULT '',
    sides               INTEGER  NOT NULL,
    count               INTEGER  NOT NULL DEFAULT 1,
    modifier            INTEGER  NOT NULL DEFAULT 0,
    individual_results  TEXT     NOT NULL DEFAULT '[]',
    raw_total           INTEGER  NOT NULL,
    modified_total      INTEGER  NOT NULL,
    was_overridden      INTEGER  NOT NULL DEFAULT 0,
    was_player_entered  INTEGER  NOT NULL DEFAULT 0,
    created_at          DATETIME NOT NULL DEFAULT (datetime('now'))
);

-- Migration 004: Timekeeping tables

-- campaign_clock: global clock per campaign. Not FK'd to campaigns table so
-- it can be seeded in tests and pre-campaign setup without a campaigns row.
CREATE TABLE IF NOT EXISTS campaign_clock (
    campaign_id    TEXT    PRIMARY KEY,
    elapsed_rounds INTEGER NOT NULL DEFAULT 0,
    dawn_hour      INTEGER NOT NULL DEFAULT 6,
    dusk_hour      INTEGER NOT NULL DEFAULT 20
);

-- party_clocks: per-party time offset for split-party synchronisation.
CREATE TABLE IF NOT EXISTS party_clocks (
    campaign_id    TEXT    NOT NULL,
    party_id       TEXT    NOT NULL,
    elapsed_rounds INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (campaign_id, party_id),
    FOREIGN KEY (campaign_id) REFERENCES campaign_clock(campaign_id)
);

-- Migration 006: Active spell effects
CREATE TABLE IF NOT EXISTS active_effects (
    id TEXT PRIMARY KEY,
    campaign_id TEXT NOT NULL REFERENCES campaigns(id),
    spell_key TEXT NOT NULL,
    caster_id TEXT NOT NULL,
    caster_level INTEGER NOT NULL DEFAULT 1,
    target_ids TEXT NOT NULL DEFAULT '[]',
    effect_type TEXT NOT NULL DEFAULT 'modifier'
        CHECK(effect_type IN ('modifier', 'flag', 'entity', 'condition', 'instant')),
    applied_modifiers TEXT NOT NULL DEFAULT '[]',
    applied_conditions TEXT NOT NULL DEFAULT '[]',
    applied_flags TEXT NOT NULL DEFAULT '[]',
    duration_type TEXT NOT NULL DEFAULT 'rounds'
        CHECK(duration_type IN ('rounds', 'turns', 'hours', 'days', 'permanent', 'concentration')),
    duration_remaining INTEGER NOT NULL DEFAULT -1,
    requires_concentration INTEGER NOT NULL DEFAULT 0 CHECK(requires_concentration IN (0, 1)),
    is_active INTEGER NOT NULL DEFAULT 1 CHECK(is_active IN (0, 1)),
    metadata TEXT NOT NULL DEFAULT '{}',
    created_at_round INTEGER NOT NULL DEFAULT 0
);

-- parties.dungeon_id, dungeon_level, dungeon_col, dungeon_row added by migration 017.
-- parties.settlement_id, settlement_node_id added by migration 019.
-- The original dungeon_map_cells table (migration 017) was dropped by migration 039
-- after the 12b cleanup — all voxel dungeon state lives in voxel_map_cells below.

-- Migration 036: Voxel grid cell storage (3D cube-cell model)
-- Sparse storage: one row per non-default voxel cell.

CREATE TABLE IF NOT EXISTS voxel_map_cells (
    map_id TEXT NOT NULL,
    col INTEGER NOT NULL,
    row INTEGER NOT NULL,
    level INTEGER NOT NULL,
    solidity TEXT NOT NULL DEFAULT 'air',
    feature TEXT NOT NULL DEFAULT 'open',
    floor_type TEXT NOT NULL DEFAULT 'none',
    door_state TEXT NOT NULL DEFAULT '',
    door_type TEXT NOT NULL DEFAULT '',
    door_detected INTEGER NOT NULL DEFAULT 1,
    fog_state TEXT NOT NULL DEFAULT 'hidden',
    room_id INTEGER NOT NULL DEFAULT -1,
    is_corridor INTEGER NOT NULL DEFAULT 0,
    cover_value INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (map_id, col, row, level)
);

-- Migration 019: Settlement entrances
-- Settlement layout stored as JSON in settlement_data.
-- Party position is a street graph node ID, not grid coordinates.
CREATE TABLE IF NOT EXISTS settlement_entrances (
    id TEXT PRIMARY KEY,
    campaign_id TEXT NOT NULL REFERENCES campaigns(id),
    map_id TEXT NOT NULL REFERENCES hex_maps(id),
    hex_q INTEGER NOT NULL,
    hex_r INTEGER NOT NULL,
    name TEXT NOT NULL DEFAULT 'Unknown Settlement',
    market_class INTEGER NOT NULL DEFAULT 6,
    settlement_data TEXT NOT NULL DEFAULT '',
    -- Migration 025: reputation cascade + hostile gate enforcement
    parent_domain_id TEXT REFERENCES domains(id),
    barred_party_ids TEXT NOT NULL DEFAULT '[]'
);

-- Migration 025: Reputation system (Phase G-1)

CREATE TABLE IF NOT EXISTS factions (
    id TEXT PRIMARY KEY,
    campaign_id TEXT NOT NULL REFERENCES campaigns(id),
    name TEXT NOT NULL,
    alignment TEXT NOT NULL DEFAULT 'neutral'
        CHECK(alignment IN ('lawful', 'neutral', 'chaotic')),
    faction_type TEXT NOT NULL DEFAULT 'tribal',
    home_domain_id TEXT REFERENCES domains(id),
    leader_npc_id TEXT REFERENCES characters(id),
    parent_faction_id TEXT REFERENCES factions(id),
    description TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS faction_memberships (
    faction_id TEXT NOT NULL REFERENCES factions(id),
    npc_id TEXT NOT NULL REFERENCES characters(id),
    role TEXT NOT NULL DEFAULT 'member',
    PRIMARY KEY (faction_id, npc_id)
);

CREATE TABLE IF NOT EXISTS reputation_entries (
    id TEXT PRIMARY KEY,
    campaign_id TEXT NOT NULL REFERENCES campaigns(id),
    party_id TEXT NOT NULL REFERENCES parties(id),
    scope_type TEXT NOT NULL
        CHECK(scope_type IN ('faction','settlement','domain','tier_a_npc','tier_b_npc','social_group')),
    scope_id TEXT NOT NULL,
    score INTEGER NOT NULL DEFAULT 0,
    tier TEXT NOT NULL DEFAULT 'neutral'
        CHECK(tier IN ('hostile','unfriendly','neutral','indifferent','friendly')),
    last_reason TEXT NOT NULL DEFAULT '',
    last_updated TEXT NOT NULL DEFAULT (datetime('now')),
    UNIQUE(campaign_id, party_id, scope_type, scope_id)
);

CREATE TABLE IF NOT EXISTS social_groups (
    id TEXT PRIMARY KEY,
    campaign_id TEXT NOT NULL REFERENCES campaigns(id),
    name TEXT NOT NULL,
    group_type TEXT NOT NULL DEFAULT 'guild',
    description TEXT NOT NULL DEFAULT ''
);

-- domains.ruler_npc_id added by migration 025.

-- Migration 027: Henchman lifecycle (Phase G-2)

CREATE TABLE IF NOT EXISTS henchman_pools (
    id TEXT PRIMARY KEY,
    campaign_id TEXT NOT NULL REFERENCES campaigns(id),
    settlement_id TEXT NOT NULL REFERENCES settlement_entrances(id),
    generated_month INTEGER NOT NULL,
    generated_year INTEGER NOT NULL,
    total_available INTEGER NOT NULL DEFAULT 0,
    search_cost_gp INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS henchman_pool_members (
    pool_id TEXT NOT NULL REFERENCES henchman_pools(id),
    character_id TEXT NOT NULL REFERENCES characters(id),
    allotment_week INTEGER NOT NULL DEFAULT 1,
    is_hired INTEGER NOT NULL DEFAULT 0 CHECK(is_hired IN (0, 1)),
    PRIMARY KEY (pool_id, character_id)
);

CREATE TABLE IF NOT EXISTS henchman_state (
    character_id TEXT PRIMARY KEY REFERENCES characters(id),
    morale_score INTEGER NOT NULL DEFAULT 0,
    treasure_share_percent INTEGER NOT NULL DEFAULT 15,
    unpaid_months INTEGER NOT NULL DEFAULT 0,
    is_grudging INTEGER NOT NULL DEFAULT 0 CHECK(is_grudging IN (0, 1)),
    is_fanatic INTEGER NOT NULL DEFAULT 0 CHECK(is_fanatic IN (0, 1)),
    hired_month INTEGER NOT NULL DEFAULT 0,
    hired_year INTEGER NOT NULL DEFAULT 0,
    departure_reason TEXT NOT NULL DEFAULT '',
    departure_settlement_id TEXT REFERENCES settlement_entrances(id),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);


-- ---------------------------------------------------------------------------
-- Event scheduler (Migration 028)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS scheduled_events (
    event_id        TEXT    PRIMARY KEY,
    campaign_id     TEXT    NOT NULL REFERENCES campaigns(id),
    fire_time       INTEGER NOT NULL,
    event_type      TEXT    NOT NULL,
    owner_id        TEXT    NOT NULL DEFAULT '',
    data_json       TEXT    NOT NULL DEFAULT '{}',
    priority        INTEGER NOT NULL DEFAULT 20,
    cancelled       INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_scheduled_events_fire_time
    ON scheduled_events(campaign_id, fire_time);

CREATE INDEX IF NOT EXISTS idx_scheduled_events_owner
    ON scheduled_events(campaign_id, owner_id);

CREATE TABLE IF NOT EXISTS auto_pause_config (
    campaign_id     TEXT    NOT NULL REFERENCES campaigns(id),
    event_category  TEXT    NOT NULL,
    pause_tier      INTEGER NOT NULL DEFAULT 1,
    PRIMARY KEY (campaign_id, event_category)
);


-- ---------------------------------------------------------------------------
-- Shop inventory and commissions (Migration 029)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS shop_inventory (
    id                  TEXT    PRIMARY KEY,
    campaign_id         TEXT    NOT NULL REFERENCES campaigns(id),
    settlement_id       TEXT    NOT NULL,
    poi_id              TEXT    NOT NULL,
    item_key            TEXT    NOT NULL,
    quantity_available  INTEGER NOT NULL DEFAULT 0,
    generated_at_round  INTEGER NOT NULL DEFAULT 0,
    UNIQUE(campaign_id, poi_id, item_key)
);

CREATE INDEX IF NOT EXISTS idx_shop_inventory_poi
    ON shop_inventory(campaign_id, poi_id);

CREATE TABLE IF NOT EXISTS commissions (
    id                  TEXT    PRIMARY KEY,
    campaign_id         TEXT    NOT NULL REFERENCES campaigns(id),
    settlement_id       TEXT    NOT NULL,
    poi_id              TEXT    NOT NULL,
    character_id        TEXT    NOT NULL REFERENCES characters(id),
    item_key            TEXT    NOT NULL,
    quantity            INTEGER NOT NULL DEFAULT 1,
    cost_cp             INTEGER NOT NULL DEFAULT 0,
    ordered_at_round    INTEGER NOT NULL DEFAULT 0,
    ready_at_round      INTEGER NOT NULL DEFAULT 0,
    picked_up           INTEGER NOT NULL DEFAULT 0 CHECK(picked_up IN (0, 1))
);

CREATE INDEX IF NOT EXISTS idx_commissions_poi
    ON commissions(campaign_id, poi_id);

CREATE INDEX IF NOT EXISTS idx_commissions_character
    ON commissions(campaign_id, character_id);


-- ---------------------------------------------------------------------------
-- Settlement PoI visit log (Migration 030; known_city_routes dropped by 041)
-- ---------------------------------------------------------------------------
-- visited_pois retained for narrative tracking only (quest/dialogue references
-- like "have you been to X?"); does NOT gate menu visibility in v2 settlement
-- exploration UI.

CREATE TABLE IF NOT EXISTS visited_pois (
    id                  TEXT    PRIMARY KEY,
    campaign_id         TEXT    NOT NULL REFERENCES campaigns(id),
    settlement_id       TEXT    NOT NULL,
    poi_id              TEXT    NOT NULL,
    discovered_at_round INTEGER NOT NULL DEFAULT 0,
    discovery_method    TEXT    NOT NULL DEFAULT 'visited',
    UNIQUE(campaign_id, settlement_id, poi_id)
);

CREATE INDEX IF NOT EXISTS idx_visited_pois_lookup
    ON visited_pois(campaign_id, settlement_id);

-- ============================================================================
-- Abandoned Characters (migration 031)
-- ============================================================================

CREATE TABLE IF NOT EXISTS abandoned_characters (
    character_id TEXT    NOT NULL,
    dungeon_id   TEXT    NOT NULL,
    level_num    INTEGER NOT NULL DEFAULT 1,
    col          INTEGER NOT NULL DEFAULT 0,
    row          INTEGER NOT NULL DEFAULT 0,
    abandoned_at INTEGER NOT NULL DEFAULT 0,
    resolved     INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (character_id, dungeon_id)
);

-- ============================================================================
-- Location Caches (migration 032; migration 037 extends dungeon keys to 3D)
-- ============================================================================
-- location_key formats:
--   hex:             "hex:<q>,<r>"
--   dungeon_cell:    "dungeon:<dungeon_id>:cell:<col>,<row>,<level>"   -- level axis added in migration 037
--   settlement_node: "settlement:<settlement_id>:poi:<poi_id>"

CREATE TABLE IF NOT EXISTS location_caches (
    id TEXT PRIMARY KEY,
    campaign_id TEXT NOT NULL REFERENCES campaigns(id),
    location_type TEXT NOT NULL CHECK(location_type IN ('hex', 'dungeon_cell', 'settlement_node')),
    location_key TEXT NOT NULL,
    cache_variant TEXT NOT NULL CHECK(cache_variant IN ('loose', 'locked_container', 'hidden_wilderness')),
    container_item_id TEXT REFERENCES inventory_items(id) ON DELETE SET NULL,
    is_persistent INTEGER NOT NULL DEFAULT 0,
    decay_check_day INTEGER DEFAULT NULL,
    created_at_day INTEGER NOT NULL,
    raid_monthly_modifier INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS location_caches_by_location
    ON location_caches(campaign_id, location_type, location_key);

CREATE INDEX IF NOT EXISTS location_caches_by_decay_day
    ON location_caches(decay_check_day)
    WHERE decay_check_day IS NOT NULL;

-- ============================================================================
-- Character Preferences (migration 033)
-- ============================================================================

CREATE TABLE IF NOT EXISTS character_preferences (
    character_id TEXT NOT NULL PRIMARY KEY REFERENCES characters(id) ON DELETE CASCADE,
    preferred_tags TEXT NOT NULL DEFAULT '[]'
);

-- ============================================================================
-- Familiars (migration 044)
-- ============================================================================
-- A familiar is a magical animal companion bonded to a single master (PC).
-- Form determines body (AC, movement, attacks, special abilities); HD, max HP,
-- INT, and proficiency count are derived from master and cached here.
-- See generation/gdd-familiars.md.

CREATE TABLE IF NOT EXISTS familiars (
    id TEXT PRIMARY KEY,
    campaign_id TEXT NOT NULL REFERENCES campaigns(id),
    master_character_id TEXT NOT NULL REFERENCES characters(id),
    form_key TEXT NOT NULL,
    cosmetic_species TEXT NOT NULL DEFAULT '',
    name TEXT NOT NULL DEFAULT '',
    hp_current INTEGER NOT NULL DEFAULT 1,
    hp_max_cached INTEGER NOT NULL DEFAULT 1,
    -- HD progression (derived from master level — see gdd-familiars.md §3.3)
    hd_dice INTEGER NOT NULL DEFAULT 0,
    hd_modifier_hp INTEGER NOT NULL DEFAULT 0,
    is_half_hd INTEGER NOT NULL DEFAULT 1 CHECK(is_half_hd IN (0, 1)),
    -- Attack / save progression (derived from master level via HD)
    attack_save_class TEXT NOT NULL DEFAULT 'NM' CHECK(attack_save_class IN ('NM', 'fighter')),
    attack_save_level INTEGER NOT NULL DEFAULT 0,
    damage_bonus INTEGER NOT NULL DEFAULT 0,
    int_cached INTEGER NOT NULL DEFAULT 10,
    proficiency_count_cached INTEGER NOT NULL DEFAULT 0,
    proficiencies_chosen TEXT NOT NULL DEFAULT '[]',
    is_alive INTEGER NOT NULL DEFAULT 1 CHECK(is_alive IN (0, 1)),
    bonded_at_master_level INTEGER NOT NULL DEFAULT 1,
    death_save_pending INTEGER NOT NULL DEFAULT 0 CHECK(death_save_pending IN (0, 1)),
    position_voxel_x INTEGER NOT NULL DEFAULT 0,
    position_voxel_y INTEGER NOT NULL DEFAULT 0,
    position_voxel_z INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_familiars_master
    ON familiars(master_character_id);

CREATE UNIQUE INDEX IF NOT EXISTS idx_familiars_living_per_master
    ON familiars(master_character_id) WHERE is_alive = 1;
