-- ACKS Arbiter — Canonical Database Schema
-- This file always reflects the current database state after all migrations.
-- Do NOT edit this file directly. Add a new migration in db/migrations/ instead.
-- Last migration applied: 019
--
-- To rebuild from scratch: delete campaign.db and relaunch the game.

CREATE TABLE IF NOT EXISTS schema_migrations (
    version INTEGER PRIMARY KEY,
    applied_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Migration 001: Initial schema
-- Creates all Tier 1 tables: campaigns, characters, parties, party_members,
-- character_conditions, character_proficiencies, inventory_items, character_spells,
-- hex_maps, hex_cells, domains.

CREATE TABLE IF NOT EXISTS campaigns (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    world_name TEXT NOT NULL DEFAULT '',
    calendar_day INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    is_active INTEGER NOT NULL DEFAULT 1 CHECK(is_active IN (0, 1))
);

CREATE TABLE IF NOT EXISTS characters (
    id TEXT PRIMARY KEY,
    campaign_id TEXT NOT NULL REFERENCES campaigns(id),
    name TEXT NOT NULL,
    character_type TEXT NOT NULL DEFAULT 'pc'
        CHECK(character_type IN ('pc', 'henchman', 'npc')),
    persistence_tier TEXT NOT NULL DEFAULT 'full'
        CHECK(persistence_tier IN ('full', 'named', 'transient')),
    race TEXT NOT NULL DEFAULT 'human',
    character_class TEXT NOT NULL DEFAULT 'fighter',
    level INTEGER NOT NULL DEFAULT 1,
    xp INTEGER NOT NULL DEFAULT 0,
    -- Four ACKS 1e combat progression types. "crusader" is ACKS II only.
    combat_progression TEXT NOT NULL DEFAULT 'fighter'
        CHECK(combat_progression IN ('fighter', 'cleric', 'thief', 'mage')),
    strength INTEGER NOT NULL DEFAULT 10,
    intelligence INTEGER NOT NULL DEFAULT 10,
    wisdom INTEGER NOT NULL DEFAULT 10,
    dexterity INTEGER NOT NULL DEFAULT 10,
    constitution INTEGER NOT NULL DEFAULT 10,
    charisma INTEGER NOT NULL DEFAULT 10,
    hp_max INTEGER NOT NULL DEFAULT 1,
    hp_current INTEGER NOT NULL DEFAULT 1,
    armor_class INTEGER NOT NULL DEFAULT 0,
    attack_throw INTEGER NOT NULL DEFAULT 10,
    is_dead INTEGER NOT NULL DEFAULT 0 CHECK(is_dead IN (0, 1)),
    is_active INTEGER NOT NULL DEFAULT 1 CHECK(is_active IN (0, 1)),
    employer_id TEXT REFERENCES characters(id),
    loyalty_score INTEGER,
    wage_gp_per_month INTEGER,
    -- Migration 005 additions
    save_petrification INTEGER NOT NULL DEFAULT 15,
    save_poison_death INTEGER NOT NULL DEFAULT 14,
    save_blast_breath INTEGER NOT NULL DEFAULT 16,
    save_staffs_wands INTEGER NOT NULL DEFAULT 16,
    save_spells INTEGER NOT NULL DEFAULT 17,
    base_movement INTEGER NOT NULL DEFAULT 120,
    hit_die_type TEXT NOT NULL DEFAULT '1d8',
    max_level INTEGER NOT NULL DEFAULT 14,
    xp_for_next_level INTEGER NOT NULL DEFAULT 2000,
    xp_adjustment_percent INTEGER NOT NULL DEFAULT 0,
    title TEXT NOT NULL DEFAULT '',
    alignment TEXT NOT NULL DEFAULT 'neutral',
    current_age INTEGER NOT NULL DEFAULT 0,
    age_category TEXT NOT NULL DEFAULT 'adult',
    languages TEXT NOT NULL DEFAULT '[]',
    personality TEXT NOT NULL DEFAULT '{}',
    is_incapacitated INTEGER NOT NULL DEFAULT 0,
    -- Migration 008 additions
    portrait_id TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    -- Migration 009 additions
    sex TEXT NOT NULL DEFAULT 'male' CHECK(sex IN ('male', 'female'))
);

CREATE TABLE IF NOT EXISTS parties (
    id TEXT PRIMARY KEY,
    campaign_id TEXT NOT NULL REFERENCES campaigns(id),
    name TEXT NOT NULL DEFAULT 'The Party',
    current_map_id TEXT,
    current_hex_q INTEGER,
    current_hex_r INTEGER,
    current_location_type TEXT NOT NULL DEFAULT 'wilderness'
        CHECK(current_location_type IN ('wilderness', 'dungeon', 'settlement', 'sea')),
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS party_members (
    party_id TEXT NOT NULL REFERENCES parties(id),
    character_id TEXT NOT NULL REFERENCES characters(id),
    formation_slot TEXT NOT NULL DEFAULT 'middle'
        CHECK(formation_slot IN ('point', 'front', 'middle', 'rear')),
    joined_at TEXT NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY (party_id, character_id)
);

CREATE TABLE IF NOT EXISTS character_conditions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    character_id TEXT NOT NULL REFERENCES characters(id),
    condition_name TEXT NOT NULL,
    applied_at_round INTEGER,
    expires_at_round INTEGER,
    source_id TEXT
);

CREATE TABLE IF NOT EXISTS character_proficiencies (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    character_id TEXT NOT NULL REFERENCES characters(id),
    proficiency_key TEXT NOT NULL,
    rank INTEGER NOT NULL DEFAULT 1,
    slot_type TEXT NOT NULL DEFAULT 'general'
        CHECK(slot_type IN ('class', 'general')),
    -- Migration 007 additions
    selections_count INTEGER NOT NULL DEFAULT 1,
    specialization TEXT NOT NULL DEFAULT ''
);

-- encumbrance_units: weight in 1/1000-stone units (1 stone = 1000 units = ~10 lbs)
-- Examples: dagger=167, sword=1000, plate armour=6000, coin/gem=1
CREATE TABLE IF NOT EXISTS inventory_items (
    id TEXT PRIMARY KEY,
    character_id TEXT NOT NULL REFERENCES characters(id),
    item_key TEXT NOT NULL,
    name TEXT NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    encumbrance_units INTEGER NOT NULL DEFAULT 0,
    slot TEXT NOT NULL DEFAULT 'pack'
        CHECK(slot IN (
            'hands_main', 'hands_off',
            'body', 'head', 'belt', 'feet', 'hands_worn', 'cloak',
            'accessory_1', 'accessory_2', 'accessory_3', 'accessory_4', 'accessory_5',
            'pack', 'mount'
        )),
    is_equipped INTEGER NOT NULL DEFAULT 0 CHECK(is_equipped IN (0, 1)),
    notes TEXT NOT NULL DEFAULT '',
    -- Migration 005 additions
    item_category TEXT NOT NULL DEFAULT 'gear',
    is_magical INTEGER NOT NULL DEFAULT 0,
    magical_bonus INTEGER NOT NULL DEFAULT 0,
    weapon_damage TEXT NOT NULL DEFAULT '',
    armor_ac_bonus INTEGER NOT NULL DEFAULT 0,
    is_heavy INTEGER NOT NULL DEFAULT 0,
    -- Migration 006 additions
    damage_type TEXT NOT NULL DEFAULT 'physical',
    material TEXT NOT NULL DEFAULT '',
    -- Migration 010 additions
    container_id TEXT NOT NULL DEFAULT '',
    -- Migration 011: slot expanded to include feet, hands_worn, accessory_1-5
    -- Migration 012 additions
    uses_remaining INTEGER NOT NULL DEFAULT -1
);

-- character_spells: active spell repertoire for all casters.
-- is_in_repertoire is always 1 for new rows (enforced by app logic).
-- is_memorized and memorized_slots are legacy; use character_spell_slots_expended instead.
CREATE TABLE IF NOT EXISTS character_spells (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    character_id TEXT NOT NULL REFERENCES characters(id),
    spell_key TEXT NOT NULL,
    spell_level INTEGER NOT NULL,
    is_memorized INTEGER NOT NULL DEFAULT 0 CHECK(is_memorized IN (0, 1)),
    is_in_repertoire INTEGER NOT NULL DEFAULT 1 CHECK(is_in_repertoire IN (0, 1)),
    memorized_slots INTEGER NOT NULL DEFAULT 0
);

-- Migration 018: Arcane spell formula tracking
-- Arcane only: spells for which the character possesses the formula.
-- Distinct from active repertoire (character_spells). Enables "known but not active" state.
CREATE TABLE IF NOT EXISTS character_spell_formulas (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    character_id TEXT NOT NULL REFERENCES characters(id),
    spell_key TEXT NOT NULL,
    spell_level INTEGER NOT NULL,
    UNIQUE(character_id, spell_key)
);

-- Migration 018: Daily expended spell slot tracking per level.
-- Replaces the per-spell is_memorized proxy. Cleared on rest.
CREATE TABLE IF NOT EXISTS character_spell_slots_expended (
    character_id TEXT NOT NULL REFERENCES characters(id),
    spell_level INTEGER NOT NULL,
    expended INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (character_id, spell_level)
);

CREATE TABLE IF NOT EXISTS hex_maps (
    id TEXT PRIMARY KEY,
    campaign_id TEXT NOT NULL REFERENCES campaigns(id),
    name TEXT NOT NULL,
    scale TEXT NOT NULL CHECK(scale IN ('campaign_24mi', 'regional_6mi', 'local_15mi')),
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- fog_state is per-campaign (scoped through hex_maps.campaign_id)
CREATE TABLE IF NOT EXISTS hex_cells (
    map_id TEXT NOT NULL REFERENCES hex_maps(id),
    q INTEGER NOT NULL,
    r INTEGER NOT NULL,
    elevation TEXT NOT NULL DEFAULT 'flat'
        CHECK(elevation IN ('flat', 'hills', 'mountains')),
    biome TEXT NOT NULL DEFAULT 'clear'
        CHECK(biome IN ('clear', 'woods', 'jungle', 'swamp', 'desert')),
    water TEXT NOT NULL DEFAULT ''
        CHECK(water IN ('', 'river', 'ocean')),
    civilization TEXT NOT NULL DEFAULT 'wilderness'
        CHECK(civilization IN ('civilized', 'borderlands', 'wilderness')),
    has_city INTEGER NOT NULL DEFAULT 0 CHECK(has_city IN (0, 1)),
    original_biome TEXT NOT NULL DEFAULT '',
    fog_state TEXT NOT NULL DEFAULT 'hidden'
        CHECK(fog_state IN ('hidden', 'explored', 'visible')),
    PRIMARY KEY (map_id, q, r)
);

CREATE TABLE IF NOT EXISTS domains (
    id TEXT PRIMARY KEY,
    campaign_id TEXT NOT NULL REFERENCES campaigns(id),
    name TEXT NOT NULL,
    owner_character_id TEXT REFERENCES characters(id),
    location_map_id TEXT REFERENCES hex_maps(id),
    location_hex_q INTEGER,
    location_hex_r INTEGER,
    -- Three ACKS territory classifications only
    territory_type TEXT NOT NULL DEFAULT 'wilderness'
        CHECK(territory_type IN ('civilized', 'borderlands', 'wilderness')),
    urban_families INTEGER NOT NULL DEFAULT 0,
    peasant_families INTEGER NOT NULL DEFAULT 0,
    morale INTEGER NOT NULL DEFAULT 0,
    garrison_troops INTEGER NOT NULL DEFAULT 0,
    revenue_gp INTEGER NOT NULL DEFAULT 0,
    expenses_gp INTEGER NOT NULL DEFAULT 0,
    net_income_gp INTEGER NOT NULL DEFAULT 0,
    domain_xp_this_month INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Migration 005: Character powers (modular power system)
CREATE TABLE IF NOT EXISTS character_powers (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    character_id TEXT NOT NULL REFERENCES characters(id),
    power_id TEXT NOT NULL,
    unlock_level INTEGER NOT NULL DEFAULT 1,
    conditions TEXT NOT NULL DEFAULT '[]',
    progression_data TEXT NOT NULL DEFAULT '{}',
    is_active INTEGER NOT NULL DEFAULT 1 CHECK(is_active IN (0, 1))
);

-- Migration 002: Override system tables

-- override_log: append-only audit trail. Never delete rows.
CREATE TABLE IF NOT EXISTS override_log (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    campaign_id TEXT NOT NULL REFERENCES campaigns(id),
    game_day INTEGER NOT NULL DEFAULT 0,
    game_round INTEGER NOT NULL DEFAULT 0,
    applied_at TEXT NOT NULL DEFAULT (datetime('now')),
    override_type TEXT NOT NULL,
    target_id TEXT NOT NULL DEFAULT '',
    field_changed TEXT NOT NULL DEFAULT '',
    old_value TEXT NOT NULL DEFAULT '',
    new_value TEXT NOT NULL DEFAULT ''
);

-- game_snapshots: capped at 10 per campaign (oldest auto-pruned on 11th save).
CREATE TABLE IF NOT EXISTS game_snapshots (
    id TEXT PRIMARY KEY,
    campaign_id TEXT NOT NULL REFERENCES campaigns(id),
    label TEXT NOT NULL,
    snapshot_data TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- dungeon_entrances: hex placement record; dungeon_data populated by layout generator.
CREATE TABLE IF NOT EXISTS dungeon_entrances (
    id TEXT PRIMARY KEY,
    campaign_id TEXT NOT NULL REFERENCES campaigns(id),
    map_id TEXT NOT NULL REFERENCES hex_maps(id),
    hex_q INTEGER NOT NULL,
    hex_r INTEGER NOT NULL,
    name TEXT NOT NULL DEFAULT 'Unknown Dungeon',
    dungeon_data TEXT NOT NULL DEFAULT ''
);

-- Migration 003: Dice roll log
-- Per-session only. Cleared on session end. Capped at 200 rows (DiceSystem auto-prunes oldest).

CREATE TABLE IF NOT EXISTS dice_rolls (
    id                  INTEGER  PRIMARY KEY AUTOINCREMENT,
    game_day            INTEGER  NOT NULL DEFAULT 0,
    roll_type           TEXT     NOT NULL DEFAULT '',
    sides               INTEGER  NOT NULL,
    count               INTEGER  NOT NULL DEFAULT 1,
    modifier            INTEGER  NOT NULL DEFAULT 0,
    individual_results  TEXT     NOT NULL DEFAULT '[]',
    raw_total           INTEGER  NOT NULL,
    modified_total      INTEGER  NOT NULL,
    was_overridden      INTEGER  NOT NULL DEFAULT 0,
    was_player_entered  INTEGER  NOT NULL DEFAULT 0,
    created_at          DATETIME NOT NULL DEFAULT (datetime('now'))
);

-- Migration 004: Timekeeping tables

-- campaign_clock: global clock per campaign. Not FK'd to campaigns table so
-- it can be seeded in tests and pre-campaign setup without a campaigns row.
CREATE TABLE IF NOT EXISTS campaign_clock (
    campaign_id    TEXT    PRIMARY KEY,
    elapsed_rounds INTEGER NOT NULL DEFAULT 0,
    dawn_hour      INTEGER NOT NULL DEFAULT 6,
    dusk_hour      INTEGER NOT NULL DEFAULT 20
);

-- party_clocks: per-party time offset for split-party synchronisation.
CREATE TABLE IF NOT EXISTS party_clocks (
    campaign_id    TEXT    NOT NULL,
    party_id       TEXT    NOT NULL,
    elapsed_rounds INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (campaign_id, party_id),
    FOREIGN KEY (campaign_id) REFERENCES campaign_clock(campaign_id)
);

-- Migration 006: Active spell effects
CREATE TABLE IF NOT EXISTS active_effects (
    id TEXT PRIMARY KEY,
    campaign_id TEXT NOT NULL REFERENCES campaigns(id),
    spell_key TEXT NOT NULL,
    caster_id TEXT NOT NULL,
    caster_level INTEGER NOT NULL DEFAULT 1,
    target_ids TEXT NOT NULL DEFAULT '[]',
    effect_type TEXT NOT NULL DEFAULT 'modifier'
        CHECK(effect_type IN ('modifier', 'flag', 'entity', 'condition', 'instant')),
    applied_modifiers TEXT NOT NULL DEFAULT '[]',
    applied_conditions TEXT NOT NULL DEFAULT '[]',
    applied_flags TEXT NOT NULL DEFAULT '[]',
    duration_type TEXT NOT NULL DEFAULT 'rounds'
        CHECK(duration_type IN ('rounds', 'turns', 'hours', 'days', 'permanent', 'concentration')),
    duration_remaining INTEGER NOT NULL DEFAULT -1,
    requires_concentration INTEGER NOT NULL DEFAULT 0 CHECK(requires_concentration IN (0, 1)),
    is_active INTEGER NOT NULL DEFAULT 1 CHECK(is_active IN (0, 1)),
    metadata TEXT NOT NULL DEFAULT '{}',
    created_at_round INTEGER NOT NULL DEFAULT 0
);

-- Migration 017: Dungeon grid cell state + party dungeon position

CREATE TABLE IF NOT EXISTS dungeon_map_cells (
    dungeon_id TEXT NOT NULL REFERENCES dungeon_entrances(id),
    level_num INTEGER NOT NULL DEFAULT 1,
    col INTEGER NOT NULL,
    row INTEGER NOT NULL,
    door_state TEXT NOT NULL DEFAULT 'closed',
    fog_state TEXT NOT NULL DEFAULT 'hidden'
        CHECK(fog_state IN ('hidden', 'explored', 'visible')),
    PRIMARY KEY (dungeon_id, level_num, col, row)
);

-- parties.dungeon_id, dungeon_level, dungeon_col, dungeon_row added by migration 017.
-- parties.settlement_id, settlement_node_id added by migration 019.
-- ALTER TABLE statements omitted here; they are in the migration files.

-- Migration 019: Settlement entrances
-- Settlement layout stored as JSON in settlement_data.
-- Party position is a street graph node ID, not grid coordinates.
CREATE TABLE IF NOT EXISTS settlement_entrances (
    id TEXT PRIMARY KEY,
    campaign_id TEXT NOT NULL REFERENCES campaigns(id),
    map_id TEXT NOT NULL REFERENCES hex_maps(id),
    hex_q INTEGER NOT NULL,
    hex_r INTEGER NOT NULL,
    name TEXT NOT NULL DEFAULT 'Unknown Settlement',
    market_class INTEGER NOT NULL DEFAULT 6,
    settlement_data TEXT NOT NULL DEFAULT ''
);
