class_name HpRollPanel
extends VBoxContainer

## Step 4 — Hit Point Rolling.
##
## Shows the class hit die and CON modifier. Player rolls interactively.
## HP = max(1, die_roll + CON_modifier).
## Optional "Max HP" toggle (house rule — logged via override system).
##
## CharacterData is generated by the flow controller before entering this step.
## This panel overwrites the auto-rolled HP with the interactive result.


var _state: Dictionary = {}
var _class_registry: ClassRegistry

var _die_info_label: Label
var _result_label: Label
var _roll_button: Button
var _max_hp_check: CheckBox
var _reroll_button: Button
var _rolling: bool = false


func setup(state: Dictionary, class_registry: ClassRegistry) -> void:
	_state = state
	_class_registry = class_registry
	if get_child_count() == 0:
		_build_ui()
	_refresh_display()


func is_complete() -> bool:
	return _state.has("hp_rolled")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

func _get_die_sides() -> int:
	var class_id: String = _state.get("class_id", "")
	var hit_die: String = _class_registry.get_hit_die(class_id)
	if "d" in hit_die:
		var parts := hit_die.split("d")
		if parts.size() >= 2 and parts[1].is_valid_int():
			return int(parts[1])
	return 8


func _get_hit_die_str() -> String:
	var class_id: String = _state.get("class_id", "")
	return _class_registry.get_hit_die(class_id)


func _get_con_modifier() -> int:
	var character: CharacterData = _state.get("character")
	if character == null:
		var effective: Dictionary = _state.get("traded_scores", {})
		if effective.is_empty():
			effective = _state.get("scores", {})
		return CharacterData.ability_modifier(int(effective.get("CON", 10)))
	return CharacterData.ability_modifier(character.constitution)


# ---------------------------------------------------------------------------
# UI Construction
# ---------------------------------------------------------------------------

func _build_ui() -> void:
	add_theme_constant_override("separation", 12)

	var class_id: String = _state.get("class_id", "")
	var cls_name: String = _class_registry.get_class_def(class_id).get("class_name",
		class_id.capitalize())

	var header := Label.new()
	header.text = "Roll your starting hit points."
	add_child(header)

	_die_info_label = Label.new()
	_die_info_label.text = ""
	_die_info_label.add_theme_font_size_override("font_size", 14)
	add_child(_die_info_label)

	_result_label = Label.new()
	_result_label.text = ""
	_result_label.add_theme_font_size_override("font_size", 16)
	add_child(_result_label)

	var btn_row := HBoxContainer.new()
	btn_row.add_theme_constant_override("separation", 8)
	add_child(btn_row)

	_roll_button = Button.new()
	_roll_button.text = "Roll Hit Points"
	_roll_button.pressed.connect(_on_roll_pressed)
	btn_row.add_child(_roll_button)

	_reroll_button = Button.new()
	_reroll_button.text = "Re-Roll"
	_reroll_button.visible = false
	_reroll_button.pressed.connect(_on_roll_pressed)
	btn_row.add_child(_reroll_button)

	_max_hp_check = CheckBox.new()
	_max_hp_check.text = "Max HP at Level 1 (house rule)"
	_max_hp_check.toggled.connect(_on_max_hp_toggled)
	add_child(_max_hp_check)


func _refresh_display() -> void:
	var hit_die := _get_hit_die_str()
	var con_mod := _get_con_modifier()
	var mod_str := ("+%d" % con_mod) if con_mod >= 0 else str(con_mod)
	_die_info_label.text = "Hit Die: %s  |  CON Modifier: %s" % [hit_die, mod_str]

	if _state.has("hp_rolled"):
		var hp: int = _state.get("hp_rolled", 0)
		var raw: int = _state.get("hp_raw_roll", hp)
		var con_mod_val := _get_con_modifier()
		_result_label.text = "HP: %d  (rolled %d %s %s = %d, minimum 1)" % [
			hp, raw, "+" if con_mod_val >= 0 else "", con_mod_val, maxi(raw + con_mod_val, 1)]
		_reroll_button.visible = true
		_roll_button.visible = false
	else:
		_result_label.text = ""
		_reroll_button.visible = false
		_roll_button.visible = true


# ---------------------------------------------------------------------------
# Roll logic (async)
# ---------------------------------------------------------------------------

func _on_roll_pressed() -> void:
	if _rolling:
		return
	_rolling = true
	_roll_button.disabled = true
	_reroll_button.disabled = true

	var sides := _get_die_sides()
	var hit_die := _get_hit_die_str()
	var result: RollResult = await DiceSystem.player_roll(sides, 1, 0,
		"hit_points", "Roll Hit Points (%s)" % hit_die)

	var con_mod := _get_con_modifier()
	var raw := result.modified_total
	var hp := maxi(raw + con_mod, 1)

	_state["hp_rolled"] = hp
	_state["hp_raw_roll"] = raw
	_state["max_hp_override"] = false
	_max_hp_check.button_pressed = false

	# Apply to CharacterData if available
	var character: CharacterData = _state.get("character")
	if character != null:
		character.hp_max = hp
		character.hp_current = hp

	_rolling = false
	_roll_button.disabled = false
	_reroll_button.disabled = false
	_refresh_display()


func _on_max_hp_toggled(pressed: bool) -> void:
	if pressed:
		var sides := _get_die_sides()
		var con_mod := _get_con_modifier()
		var hp := maxi(sides + con_mod, 1)
		_state["hp_rolled"] = hp
		_state["max_hp_override"] = true
		_state.erase("hp_raw_roll")

		# Log as override
		GameState.dice_overrides["hit_points"] = sides

		var character: CharacterData = _state.get("character")
		if character != null:
			character.hp_max = hp
			character.hp_current = hp
	else:
		_state["max_hp_override"] = false
		if GameState.dice_overrides.has("hit_points"):
			GameState.dice_overrides.erase("hit_points")
		# Clear so player must re-roll
		_state.erase("hp_rolled")
		_state.erase("hp_raw_roll")
		var character: CharacterData = _state.get("character")
		if character != null:
			character.hp_max = 0
			character.hp_current = 0
	_refresh_display()
